### ISSUE TITLE
test_solve is failing on current Debian testing (buster)

### ISSUE THREAD

**Issue by giuliopaci** [MattShannon/bandmat#5]
Hi,
   I just tried to install bandmat on a current updates Debian testing (buster, as of Nov 15, 2017) with the following commands:

```
sudo apt-get install python-numpy python-scipy
```
followed by

```
virtualenv --system-site-packages env
env/bin/pip install bandmat
```

which produced

```
Running virtualenv with interpreter /usr/bin/python2
New python executable in /pathtotheworkingdirectory/env/bin/python2
Also creating executable in /pathtotheworkingdirectory/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
myusername@odino:/pathtotheworkingdirectory$ env/bin/pip install bandmat
Collecting bandmat
Requirement already satisfied: scipy>=0.9.0 in /usr/lib/python2.7/dist-packages (from bandmat)
Requirement already satisfied: numpy>=1.6.1 in /usr/lib/python2.7/dist-packages (from bandmat)
Installing collected packages: bandmat
Successfully installed bandmat-0.6
```

then I tried

```
LC_ALL=C env/bin/python -m unittest discover bandmat
```

but it is failing with

```
...........................................................................E..
======================================================================
ERROR: test_solve (bandmat.test_linalg.TestLinAlg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pathtotheworkingdirectory/env/local/lib/python2.7/site-packages/bandmat/test_linalg.py", line
    x = bla.solve(a_bm, b)
  File "bandmat/linalg.pyx", line 282, in bandmat.linalg.solve (bandmat/linalg.c:4264)
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/basic.py", line 367, in solve_banded
    b2 /= a1[1, 0]
IndexError: index 1 is out of bounds for axis 0 with size 1

----------------------------------------------------------------------
Ran 78 tests in 0.585s

FAILED (errors=1)
```

the output is not stable, sometimes I get this other error instead

```
.........................................................................../usr/lib/python2.7/dist-packages/scipy/linalg/basic.py:367: RuntimeWarning: divide by zero encountered in true_divide
  b2 /= a1[1, 0]
F..
======================================================================
FAIL: test_solve (bandmat.test_linalg.TestLinAlg)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/pathtotheworkingdirectory/env/local/lib/python2.7/site-packages/bandmat/test_linalg.py", line 279, in test_solve
    assert_allclose(bm.dot_mv(a_bm, x), b)
  File "/pathtotheworkingdirectory/env/local/lib/python2.7/site-packages/bandmat/testhelp.py", line 23, in assert_allclose
    rel_err, np.max(rel_err)))
AssertionError: items not almost equal
 ACTUAL:
array([ inf])
 DESIRED:
array([ 0.78333299])
 ABS ERR: array([ inf]) (max inf)
 REL ERR: array([ inf]) (max inf)

----------------------------------------------------------------------
Ran 78 tests in 0.572s

FAILED (failures=1)
```

Do you have any hint about how to fix the issue? Do you think it is a bug in bandmat or in its dependencies?

**Comment by MattShannon** [comment]
I'm able to replicate this on some of the windows builds.

**Comment by MattShannon** [comment]
Looks like this is a bug is scipy's solve_banded function. Opened a bug there:

https://github.com/scipy/scipy/issues/8906

Implemented a workaround, so this should be fixed (verified unit tests now pass on all platforms).
